security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_MODERATOR: [ROLE_USER]
        ROLE_ADMIN: [ROLE_MODERATOR]
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                always_use_default_target_path: true
                default_target_path: add_online
            logout:
                path: fos_user_security_logout
                target: homepage
            anonymous:    true

    access_control:
        - { path: /login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /chat/admin, role: ROLE_ADMIN }
        - { path: /chat, role: ROLE_USER } 